config/routes.rb
Issues::Application.routes.draw do
root to: 'issues#index'
  scope "/:locale" do
  get "timeline/index"
  resources :projects

  resources :issues
  
end

  

end

app/models/issue.rb
class Issue < ActiveRecord::Base
	belongs_to :project
validates :title,:description,:followers,presence: true
validates :title ,uniqueness: true
validates :description,length: {maximum: 140}
validates :description,length: {minimum: 10}

after_create :add_to_time_line

# before_save :strip_spaces_from_tags

private
def add_to_time_line
	Timeline.create!({content: "An issue was created",timelineable_id: id,timelineable_type:self.class.to_s})
	end

# def strip_spaces_from_tags
# 	self.tags.gsub! ', ' , ','
# end


end
 

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :issues
validates :name,:description,presence: true
validates :name ,uniqueness: true
validates :description,length: {maximum: 140}
validates :description,length: {minimum: 10}
end

app/models/timeline.rb
class Timeline < ActiveRecord::Base

	belongs_to :timelineable , polymorphic: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :set_locale

def set_locale
	I18n.locale= params[:locale] || I18n.default_locale
end
end

app/controllers/issues_controller.rb
class IssuesController < ApplicationController
  before_action :set_issue, only: [:show, :edit, :update, :destroy]

  # GET /issues
  # GET /issues.json
  def index
    @issues = Issue
    @issues = Issue.order(params[:sort]) if params[:sort]
    @issues = @issues.all


# code for displaying various formats
    # respond_to do |format|
    #   format.xml { render xml: @issues} # creates a xml file "issues.xml"
    #   format.rss  #create rss using index.rss.builder
    #   format.csv # create index.csv.erb 
    # end
  end

  # GET /issues/1
  # GET /issues/1.json
  def show
  end

  # GET /issues/new
  def new
    @issue = Issue.new
  end

  # GET /issues/1/edit
  def edit
  end

  # POST /issues
  # POST /issues.json
  def create
    @issue = Issue.new(issue_params)

    respond_to do |format|
      if @issue.save
        format.html { redirect_to @issue, notice: 'Issue was successfully created.' }
        format.json { render action: 'show', status: :created, location: @issue }
      else
        format.html { render action: 'new' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /issues/1
  # PATCH/PUT /issues/1.json
  def update
    respond_to do |format|
      if @issue.update(issue_params)
        format.html { redirect_to @issue, notice: 'Issue was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @issue.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /issues/1
  # DELETE /issues/1.json
  def destroy
    @issue.destroy
    respond_to do |format|
      format.html { redirect_to issues_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_issue
      @issue = Issue.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def issue_params
      params.require(:issue).permit(:title, :description, :followers)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render action: 'show', status: :created, location: @project }
      else
        format.html { render action: 'new' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/controllers/timeline_controller.rb
class TimelineController < ApplicationController
  def index
  	@timelines=Timeline.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/issues_helper.rb
module IssuesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/views/issues/_form.html.erb
<%= form_for(@issue) do |f| %>
  <% if @issue.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@issue.errors.count, "error") %> prohibited this issue from being saved:</h2>

      <ul>
      <% @issue.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :followers %><br>
    <%= f.number_field :followers %>
  </div>

<!--   <div class="field">
  <%= f.label :tags %><br>
  <%= f.text_field :tags %>
</div> -->
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/issues/_search.html.erb
<h2> Search </h2>

<%= form_tag 'search', method: :get do %> 
<%= text_field_tag :title,nil,placeholder: "search title",size: 30 %>

<ul>
<li> <%= check_box_tag :followers,1,true %>1 follower</li>
<li> <%= check_box_tag :followers,3,true %>3 follower</li>
<li> <%= check_box_tag :followers,5,true %>5+ follower</li>

</ul>

<p>

<%= date_select :created_at_start,nil %>
	&rarr;
<%= date_select :created_at_end,nil %>

<%= submit_tag "Search" %>
</p>
<% end -%>

app/views/issues/edit.html.erb
<h1>Editing issue</h1>

<%= render 'form' %>

<%= link_to 'Show', @issue %> |
<%= link_to 'Back', issues_path %>

app/views/issues/index.csv.erb
<% @issues.each do |issue| %>

<%= issue.title %>, <%=issue.created_at%>,<%= issue.description%>
<% end %>


app/views/issues/index.html.erb
<% content_for :nav do %>

<li><a href="/issues/1"> First Issue</a></li>
<% end %>

<%= render 'search'%>
<h1>Listing issues</h1>

<table>
  <thead>
    <tr>
      <th>Title <%= link_to "sort" ,issues_path(sort: "title")%></th>
      <th>Description <%= link_to "sort" ,issues_path(sort: "description ")%></th>
      <th>Followers <%= link_to "sort" ,issues_path(sort: "followers ")%></th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @issues.each do |issue| %>
      <tr>
        <td><%= issue.title %></td>
        <td><%= issue.description %></td>
        <td><%= issue.followers %></td>
        <td><%= link_to 'Show', issue_path(id: issue.id) %></td>
        <td><%= link_to 'Edit', edit_issue_path(id: issue.id) %></td>
        <td><%= link_to 'Destroy', issue_path(id: issue.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Issue', new_issue_path %>

app/views/issues/new.html.erb
<h1>New issue</h1>

<%= render 'form' %>

<%= link_to 'Back', issues_path %>

app/views/issues/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @issue.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @issue.description %>
</p>

<p>
  <strong>Followers:</strong>
  <%= @issue.followers %>
</p>

<p>
	<b>Projects:</b>
<%= link_to @issue.project.name,@issue.project%>

</p>

<%= link_to 'Edit', edit_issue_path(@issue) %> |
<%= link_to 'Back', issues_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Issues</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>

  <%= csrf_meta_tags %>
 <!--<%= auto_discovery_link_tag(:rss,issues_path(:rss)) %> for displaying rss icon pn the address bar-->
</head>
<body>
<ul>
	<li><a href="/timeline/index"><%=t "nav.timeline" %></a></li>
	<li> <a href="/issues"><%= t "nav.issues.list"%></a></li>
	<li> <a href="/issues/new"><%= t "nav.issues.new"%></a></li>
	<%= yield :nav %>
</ul>

<%= yield %>
<footer>
&copy The App
</footer>
</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Listing projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.description %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<h3> List of issues for this project</h3>
<ul>

<% @project.issues.each do |issue|  %>
<li><%= link_to issue.title ,issue %></li>

<% end %>
</ul>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>

app/views/timeline/index.html.erb
<h1>Timeline</h1>
<table>
<% @timelines.each do |timeline|%>
<tr>
<td> <%= timeline.content %> </td>
<td> <%= link_to timeline.timelineable.title, timeline.timelineable%></td>
<td> <%= time_ago_in_words timeline.created_at %>ago. </td>
</tr>
<% end %>
</table>